### ISSUE TITLE
docker: Error response from daemon: VolumeDriver.Mount: EOF.

### ISSUE THREAD

**Issue by neter-aa** [sapk/docker-volume-gluster#57]
- Plugin version (or commit ref) :from docker hub
- Docker version :Version:          18.09.0
- Plugin type : legacy/managed legacy
- Operating system:ubuntu1804

## Description

root@ocp11:~# docker run -v test:/mnt --rm -ti alpine
docker: Error response from daemon: VolumeDriver.Mount: EOF.
See 'docker run --help'.

root@ocp11:~# docker volume inspect test
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "registry.tsingj.local/plugin-gluster:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker-volumes/gluster/test",
        "Name": "test",
        "Options": {
            "voluri": "192.168.0.7,192.168.0.8,192.168.0.15,192.168.0.18:gfs"
        },
        "Scope": "global",
        "Status": {
            "TODO": "List"
        }
    }
]

root@ocp7:/mnt# gluster vol info

Volume Name: gfs
Type: Distributed-Replicate
Volume ID: e508cfb9-e426-4031-875c-95fc71b4664a
Status: Started
Snapshot Count: 0
Number of Bricks: 2 x 2 = 4
Transport-type: tcp
Bricks:
Brick1: ocp7:/mnt/gluster
Brick2: ocp8:/mnt/gluster
Brick3: ocp15:/mnt/gluster
Brick4: ocp18:/mnt/gluster
Options Reconfigured:
features.quota-deem-statfs: on
features.inode-quota: on
features.quota: on
cluster.server-quorum-type: server
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
cluster.server-quorum-ratio: 51%

## Logs

Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="2019/08/08 10:56:51 http: panic serving @: runtime error: index out of range" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="goroutine 163 [running]:" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="net/http.(*conn).serve.func1(0xc00023c320)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1746 +0xd0" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="panic(0x83ff20, 0xc2cb30)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/runtime/panic.go:513 +0x1b9" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="github.com/sapk/docker-volume-gluster/gluster/driver.parseVolURI(0x0, 0x0, 0x0, 0x4)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/go/src/app/.gopath/src/github.com/sapk/docker-volume-gluster/gluster/driver/tools.go:74 +0x1c6" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="github.com/sapk/docker-volume-gluster/gluster/driver.(*GlusterDriver).Mount(0xc0000f8820, 0xc0001f1c80, 0x0, 0x0, 0x0)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/go/src/app/.gopath/src/github.com/sapk/docker-volume-gluster/gluster/driver/driver.go:239 +0x19c" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="github.com/sapk/docker-volume-gluster/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func3(0x932f80, 0xc000336620, 0xc0002dab00)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/go/src/app/.gopath/src/github.com/sapk/docker-volume-gluster/vendor/github.com/docker/go-plugins-helpers/volume/api.go:166 +0xe9" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc0000b3780, 0x932f80, 0xc000336620, 0xc0002dab00)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1964 +0x44" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="net/http.(*ServeMux).ServeHTTP(0xc0000e9c50, 0x932f80, 0xc000336620, 0xc0002dab00)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2361 +0x127" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="net/http.serverHandler.ServeHTTP(0xc0000eb6c0, 0x932f80, 0xc000336620, 0xc0002dab00)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2741 +0xab" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="net/http.(*conn).serve(0xc00023c320, 0x933300, 0xc000334540)" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1847 +0x646" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="created by net/http.(*Server).Serve" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:51 localhost dockerd[31935]: time="2019-08-08T18:56:51+08:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2851 +0x2f5" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:52 localhost dockerd[31935]: time="2019-08-08T18:56:52+08:00" level=error msg="2019/08/08 10:56:52 Entering go-plugins-helpers mountPath" plugin=fab75fb4d1204d6750d6b14668f3d003c95da0c2963919b9fa7e5e1f7f12c96b
Aug  8 18:56:53 localhost dockerd[31935]: time="2019-08-08T18:56:53.310795637+08:00" level=error msg="Handler for POST /v1.39/containers/create returned error: VolumeDriver.Mount: EOF\n"

**Comment by unmwww** [comment]
me too.

**Comment by sapk** [comment]
This look like a duplicate of #34
